language: node_js
node_js:
  - "0.10"
env:
- NODE_ENV=test
before_install:
 - openssl aes-256-cbc -K $encrypted_368dd7c45499_key -iv $encrypted_368dd7c45499_iv -in ./tasks/travis/aws.pem.enc -out ./tasks/travis/aws.pem -d
after_success:
  - "./tasks/travis/deployment.sh"